"""
Seeds the AURA database with a full premium lifestyle catalog: categories with
editorial imagery, 140+ realistic products (many with real database-backed
variants), demo customer reviews, and demo coupons.

Safe to rerun: uses update_or_create/get_or_create throughout.

Usage: python manage.py seed_data
"""
from decimal import Decimal

from django.contrib.auth.models import User
from django.core.management.base import BaseCommand
from django.utils.text import slugify

from store.models import Category, Product, ProductVariant
from reviews.models import Review
from orders.models import Coupon


CATEGORIES = [
    dict(name='Apparel', description='Considered clothing in natural fibres, cut for longevity rather than trend.',
         image='https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=900&q=80'),
    dict(name='Outerwear', description='Coats and jackets built to be worn for a decade, not a season.',
         image='https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=900&q=80'),
    dict(name='Footwear', description='Handcrafted leather and canvas footwear, resoleable and built to last.',
         image='https://images.unsplash.com/photo-1549298916-b41d501d3772?w=900&q=80'),
    dict(name='Bags & Wallets', description='Structured leather goods finished by hand, made to age beautifully.',
         image='https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900&q=80'),
    dict(name='Jewelry & Watches', description='Solid metals and considered stones — pieces meant to be passed down.',
         image='https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=900&q=80'),
    dict(name='Accessories', description='The small details that finish a look — belts, scarves, sunglasses.',
         image='https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900&q=80'),
    dict(name='Beauty & Fragrance', description='Layered, understated scent and skincare — for the body and the room.',
         image='https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=900&q=80'),
    dict(name='Home & Living', description='Sculptural objects for the home — ceramics, glass, and hand-finished wood.',
         image='https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80'),
    dict(name='Lighting & Candles', description='Warm, considered light — from task lamps to hand-poured candles.',
         image='https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=900&q=80'),
    dict(name='Tableware & Kitchen', description='Everyday ceramics and glassware, thrown and blown by small studios.',
         image='https://images.unsplash.com/photo-1584346133934-a3afd2a33c4d?w=900&q=80'),
    dict(name='Textiles & Bath', description='Long-staple linen and Turkish cotton for the bed and bath.',
         image='https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80'),
    dict(name='Stationery & Workspace', description='Considered tools for thinking and working — paper, brass, and leather.',
         image='https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=900&q=80'),
    dict(name='Tech Accessories', description='Understated, well-made accessories for the devices you use daily.',
         image='https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=900&q=80'),
    dict(name='Travel', description='Structured luggage and travel companions built for the long haul.',
         image='https://images.unsplash.com/photo-1553531384-cc64ac80f931?w=900&q=80'),
]

APPAREL_SIZES = ['XS', 'S', 'M', 'L', 'XL']
SHOE_SIZES = ['UK6', 'UK7', 'UK8', 'UK9', 'UK10', 'UK11']
RING_SIZES = ['12', '14', '16', '18', '20']


def sizes_colors(sizes, colors, stock_each=8):
    return [{'size': s, 'color': c, 'stock': stock_each} for c in colors for s in sizes]


def colors_only(colors, stock_each=12):
    return [{'color': c, 'stock': stock_each} for c in colors]


def sizes_only(sizes, stock_each=10):
    return [{'size': s, 'stock': stock_each} for s in sizes]


PRODUCTS = [
    # ============ APPAREL ============
    dict(name='Relaxed Cotton Poplin Shirt', category='Apparel', price=4900, compare=None,
         short='Washed organic cotton poplin, boxy fit, mother-of-pearl buttons.',
         desc='A wardrobe staple made from GOTS-certified organic cotton poplin, garment-washed for a lived-in softness from the first wear. The boxy fit is intentional — designed to be tucked, layered, or worn open.',
         sku='AUR-APP-001', stock=35, featured=False, new=False, material='Organic cotton poplin', weight='240g',
         image='https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['White', 'Sky Blue'])),
    dict(name='Ribbed Merino Sweater', category='Apparel', price=9800, compare=None,
         short='Fully-fashioned merino knit in a fitted rib.',
         desc='Fully-fashioned on a flat-bed knitting machine, meaning zero waste and a seamless, second-skin fit. The extra-fine merino yarn regulates temperature naturally across seasons.',
         sku='AUR-APP-002', stock=19, featured=True, new=False, material='Extra-fine merino wool', weight='310g',
         image='https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Charcoal', 'Oatmeal'])),
    dict(name='Tapered Wool Trousers', category='Apparel', price=8400, compare=None,
         short='High-rise, tapered leg, finished with a concealed hook closure.',
         desc='A tailored trouser cut from mid-weight wool suiting, with a high rise and tapered leg that works equally well with a blazer or a knit. Fully lined through the seat and thigh.',
         sku='AUR-APP-003', stock=16, featured=False, new=False, material='Wool suiting', weight='420g',
         image='https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Black', 'Camel'])),
    dict(name='Silk Camisole', category='Apparel', price=6200, compare=None,
         short='19-momme mulberry silk, bias-cut for a fluid fall.',
         desc='Cut on the bias from 19-momme mulberry silk, this camisole falls close to the body without clinging. Adjustable straps and a French seam finish.',
         sku='AUR-APP-004', stock=22, featured=False, new=True, material='100% mulberry silk', weight='120g',
         image='https://images.unsplash.com/photo-1551163943-3f6a855d1153?w=800&q=80',
         variants=sizes_colors(['XS', 'S', 'M', 'L'], ['Ivory', 'Black'])),
    dict(name='Wide-Leg Linen Trousers', category='Apparel', price=5600, compare=None,
         short='Heavyweight European linen, elastic waist, deep pockets.',
         desc='Cut from heavyweight European linen that holds its structure through the day, these wide-leg trousers move with you rather than clinging. A concealed elastic waistband keeps the silhouette clean.',
         sku='AUR-APP-005', stock=24, featured=False, new=True, material='100% linen', weight='340g',
         image='https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Natural', 'Ink Blue'])),
    dict(name='Oversized Cotton Oxford Shirt', category='Apparel', price=4600, compare=None,
         short='Brushed cotton oxford, dropped shoulder, single chest pocket.',
         desc='A deliberately oversized oxford shirt in brushed cotton, designed to be worn buttoned to the top or open over a tee. The dropped shoulder keeps the silhouette relaxed without looking sloppy.',
         sku='AUR-APP-006', stock=28, featured=False, new=False, material='Brushed cotton', weight='260g',
         image='https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['White', 'Slate Grey'])),
    dict(name='Merino Wrap Dress', category='Apparel', price=11200, compare=13200,
         short='Fine merino jersey, self-tie waist, midi length.',
         desc='A wrap dress in fine merino jersey that layers easily under a coat in winter or stands alone in warmer months. The self-tie waist adjusts to fit.',
         sku='AUR-APP-007', stock=13, featured=True, new=False, material='Merino jersey', weight='280g',
         image='https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=800&q=80',
         variants=sizes_colors(['XS', 'S', 'M', 'L'], ['Bordeaux', 'Black'])),
    dict(name='Cotton Jersey Lounge Set', category='Apparel', price=5200, compare=None,
         short='Heavyweight cotton jersey top and trouser, matching set.',
         desc='A two-piece lounge set in heavyweight cotton jersey, brushed on the inside for softness. Designed to look considered enough to answer the door in.',
         sku='AUR-APP-008', stock=20, featured=False, new=True, material='Cotton jersey', weight='420g',
         image='https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Heather Grey', 'Clay'])),
    dict(name='Straight-Leg Selvedge Jeans', category='Apparel', price=7800, compare=None,
         short='14oz Japanese selvedge denim, straight leg, raw hem.',
         desc='Woven on vintage shuttle looms in Okayama, this 14oz selvedge denim is left raw and unwashed so it develops fades unique to the wearer over months of use.',
         sku='AUR-APP-009', stock=17, featured=False, new=False, material='Japanese selvedge denim', weight='620g',
         image='https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
         variants=sizes_only(['28', '30', '32', '34', '36'])),
    dict(name='Cashmere V-Neck Pullover', category='Apparel', price=15900, compare=None,
         short='Two-ply Mongolian cashmere, classic V-neck.',
         desc='Knitted from two-ply Mongolian cashmere for durability beyond typical single-ply knitwear, this V-neck pullover is a genuine investment piece with a timeless silhouette.',
         sku='AUR-APP-010', stock=11, featured=True, new=False, material='Two-ply cashmere', weight='290g',
         image='https://images.unsplash.com/photo-1608063615781-e2ef8c73d114?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Navy', 'Stone'])),

    # ============ OUTERWEAR ============
    dict(name='Oversized Wool Coat', category='Outerwear', price=18500, compare=22000,
         short='Double-faced wool coat with horn buttons, unlined for drape.',
         desc='Cut from a double-faced Italian wool that eliminates the need for a lining, this coat drapes rather than structures. Finished with genuine horn buttons and a hand-stitched collar.',
         sku='AUR-OUT-001', stock=7, featured=True, new=True, material='Double-faced wool', weight='1.6kg',
         image='https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&q=80',
         variants=sizes_colors(['S', 'M', 'L', 'XL'], ['Camel', 'Charcoal'])),
    dict(name='Waxed Cotton Field Jacket', category='Outerwear', price=12400, compare=None,
         short='British waxed cotton, corduroy collar, brass hardware.',
         desc='A field jacket in genuine British waxed cotton that only improves with age and re-waxing. Corduroy collar and solid brass hardware throughout.',
         sku='AUR-OUT-002', stock=14, featured=False, new=False, material='Waxed cotton, corduroy', weight='980g',
         image='https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80',
         variants=sizes_colors(['S', 'M', 'L', 'XL'], ['Olive', 'Rust'])),
    dict(name='Quilted Wool Gilet', category='Outerwear', price=8900, compare=None,
         short='Diamond-quilted wool shell, down-alternative fill.',
         desc='A sleeveless gilet in diamond-quilted wool with a recycled down-alternative fill, cut generously to layer over knitwear without bulk.',
         sku='AUR-OUT-003', stock=18, featured=False, new=True, material='Wool shell, recycled fill', weight='540g',
         image='https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80',
         variants=sizes_colors(['S', 'M', 'L', 'XL'], ['Forest Green', 'Black'])),
    dict(name='Shearling-Collar Leather Jacket', category='Outerwear', price=24500, compare=None,
         short='Full-grain lambskin, detachable shearling collar.',
         desc='A moto-inspired jacket in full-grain lambskin leather with a detachable genuine shearling collar for colder months. Fully lined with a quilted satin interior.',
         sku='AUR-OUT-004', stock=6, featured=True, new=False, material='Lambskin leather, shearling', weight='1.4kg',
         image='https://images.unsplash.com/photo-1520975954732-35dd22299614?w=800&q=80',
         variants=sizes_colors(['S', 'M', 'L'], ['Black', 'Cognac'])),
    dict(name='Packable Rain Anorak', category='Outerwear', price=6800, compare=None,
         short='Taped-seam ripstop nylon, packs into its own pocket.',
         desc='A genuinely waterproof anorak in taped-seam ripstop nylon that packs down into its own chest pocket for travel, without looking overtly technical.',
         sku='AUR-OUT-005', stock=25, featured=False, new=False, material='Ripstop nylon', weight='310g',
         image='https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80',
         variants=sizes_colors(['S', 'M', 'L', 'XL'], ['Slate', 'Sand'])),
    dict(name='Alpaca-Blend Overcoat', category='Outerwear', price=21900, compare=None,
         short='Brushed alpaca-wool blend, notched lapel, knee length.',
         desc='A knee-length overcoat in a brushed alpaca-wool blend, noticeably lighter than an equivalent wool coat for the same warmth. Fully canvassed for structure that holds its shape.',
         sku='AUR-OUT-006', stock=9, featured=False, new=True, material='Alpaca-wool blend', weight='1.5kg',
         image='https://images.unsplash.com/photo-1544923246-77307dd654cb?w=800&q=80',
         variants=sizes_colors(['S', 'M', 'L', 'XL'], ['Grey Melange'])),
    dict(name='Denim Trucker Jacket', category='Outerwear', price=6400, compare=None,
         short='12oz rigid denim, corozo buttons, chest pockets.',
         desc='A classic trucker silhouette in 12oz rigid denim that softens and fades beautifully with wear, finished with genuine corozo nut buttons.',
         sku='AUR-OUT-007', stock=21, featured=False, new=False, material='Rigid cotton denim', weight='680g',
         image='https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=800&q=80',
         variants=sizes_colors(['S', 'M', 'L', 'XL'], ['Indigo', 'Washed Black'])),

    # ============ FOOTWEAR ============
    dict(name='Hand-Stitched Leather Derby', category='Footwear', price=13900, compare=None,
         short='Goodyear-welted calfskin, resoleable construction.',
         desc='Built on a Goodyear-welted construction using full-grain calfskin, these derbies are designed to be resoled rather than replaced — a genuine decade-long investment.',
         sku='AUR-FTW-001', stock=15, featured=True, new=False, material='Full-grain calfskin', weight='920g',
         image='https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80',
         variants=sizes_only(SHOE_SIZES)),
    dict(name='Canvas Low-Top Sneaker', category='Footwear', price=4900, compare=None,
         short='Heavyweight cotton canvas, vulcanized rubber sole.',
         desc='A minimal low-top sneaker in heavyweight cotton canvas with a vulcanized rubber sole for genuine flexibility and grip, not just a fashion silhouette.',
         sku='AUR-FTW-002', stock=32, featured=False, new=True, material='Cotton canvas, rubber', weight='430g',
         image='https://images.unsplash.com/photo-1556812191-381c7e7d96d6?w=800&q=80',
         variants=sizes_colors(SHOE_SIZES, ['White', 'Black'], stock_each=6)),
    dict(name='Suede Chelsea Boot', category='Footwear', price=11200, compare=None,
         short='Italian suede, elastic gusset, leather sole.',
         desc='A Chelsea boot in soft Italian suede with an elastic side gusset for a clean pull-on fit and a genuine leather sole that can be resoled.',
         sku='AUR-FTW-003', stock=17, featured=False, new=False, material='Italian suede, leather sole', weight='860g',
         image='https://images.unsplash.com/photo-1638247025967-b4e6b3b93a17?w=800&q=80',
         variants=sizes_colors(SHOE_SIZES, ['Taupe', 'Charcoal'], stock_each=5)),
    dict(name='Espadrille Slip-On', category='Footwear', price=3400, compare=None,
         short='Jute-braided sole, cotton canvas upper, handmade in Spain.',
         desc='A traditional espadrille handmade in Spain with a genuine jute-braided sole and breathable cotton canvas upper — the definitive warm-weather slip-on.',
         sku='AUR-FTW-004', stock=26, featured=False, new=False, material='Cotton canvas, jute', weight='280g',
         image='https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80',
         variants=sizes_colors(SHOE_SIZES, ['Natural', 'Navy'], stock_each=5)),
    dict(name='Leather Penny Loafer', category='Footwear', price=9800, compare=None,
         short='Burnished calfskin, hand-sewn apron, leather sole.',
         desc='A hand-sewn apron-toe loafer in burnished calfskin with a traditional penny strap detail and a leather sole finished with a rubber half-sole for grip.',
         sku='AUR-FTW-005', stock=19, featured=True, new=False, material='Burnished calfskin', weight='780g',
         image='https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&q=80',
         variants=sizes_only(SHOE_SIZES)),
    # ============ BAGS & WALLETS ============
    dict(name='Structured Canvas Tote', category='Bags & Wallets', price=3450, compare=None,
         short='Heavyweight canvas tote with vegetable-tanned leather straps.',
         desc='Cut from 16oz waxed canvas and finished with full-grain, vegetable-tanned leather handles, built to soften and darken beautifully with use.',
         sku='AUR-BAG-001', stock=24, featured=True, new=False, material='Waxed canvas, leather', weight='680g',
         image='https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&q=80',
         variants=colors_only(['Natural', 'Black'])),
    dict(name='Minimalist Leather Wallet', category='Bags & Wallets', price=3200, compare=None,
         short='Vegetable-tanned leather, four card slots, no stitching on the spine.',
         desc='A single piece of vegetable-tanned Italian leather folded and hand-stitched into a slim four-card wallet. No branding, no excess.',
         sku='AUR-BAG-002', stock=40, featured=True, new=False, material='Vegetable-tanned leather', weight='55g',
         image='https://images.unsplash.com/photo-1601592996763-f05c9c80a7f1?w=800&q=80',
         variants=colors_only(['Tan', 'Black', 'Espresso'])),
    dict(name='Cross-Body Camera Bag', category='Bags & Wallets', price=8900, compare=None,
         short='Structured leather crossbody with brass turn-lock.',
         desc='Compact enough for daily errands, structured enough to protect a camera or tablet, built on a rigid frame with a solid brass turn-lock closure.',
         sku='AUR-BAG-003', stock=11, featured=False, new=True, material='Full-grain leather', weight='540g',
         image='https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80',
         variants=colors_only(['Chestnut', 'Black'])),
    dict(name='Italian Leather Tote', category='Bags & Wallets', price=16900, compare=19900,
         short='Vachetta leather, hand-stitched handles, structured base.',
         desc='A structured work tote in Italian vachetta leather that develops a warm honey patina with sun exposure and handling — genuinely improves with age.',
         sku='AUR-BAG-004', stock=8, featured=True, new=False, material='Vachetta leather', weight='920g',
         image='https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80',
         variants=colors_only(['Cognac', 'Black'])),
    dict(name='Woven Raffia Beach Bag', category='Bags & Wallets', price=4200, compare=None,
         short='Hand-woven raffia, leather trim, cotton lining.',
         desc='Hand-woven from natural raffia by artisans in Madagascar, trimmed in leather and fully lined in cotton canvas — as suited to the market as the beach.',
         sku='AUR-BAG-005', stock=20, featured=False, new=True, material='Raffia, leather trim', weight='410g',
         image='https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80',
         variants=[]),
    dict(name='Structured Leather Crossbody Bag', category='Bags & Wallets', price=10900, compare=None,
         short='Box-grain leather, adjustable strap, magnetic closure.',
         desc='A neat structured crossbody in box-grain leather that holds its shape without stiff interfacing, finished with a magnetic closure and an adjustable strap.',
         sku='AUR-BAG-006', stock=15, featured=False, new=False, material='Box-grain leather', weight='480g',
         image='https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80',
         variants=colors_only(['Black', 'Burgundy', 'Tan'])),
    dict(name='Zip-Around Travel Wallet', category='Bags & Wallets', price=4600, compare=None,
         short='RFID-lined leather, passport and card compartments.',
         desc='A zip-around travel wallet in pebbled leather with an RFID-blocking lining, sized to carry a passport, boarding pass, and cards in one slim case.',
         sku='AUR-BAG-007', stock=22, featured=False, new=False, material='Pebbled leather', weight='190g',
         image='https://images.unsplash.com/photo-1620109176813-e91290f6c795?w=800&q=80',
         variants=colors_only(['Black', 'Navy'])),

    # ============ JEWELRY & WATCHES ============
    dict(name='Sterling Signet Ring', category='Jewelry & Watches', price=5600, compare=None,
         short='Solid sterling silver, hand-polished, unengraved face.',
         desc='Cast from solid sterling silver and hand-polished to a soft satin finish, this signet is left unengraved so it can be personalised or worn plain.',
         sku='AUR-JEW-001', stock=12, featured=False, new=True, material='Sterling silver', weight='9g',
         image='https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80',
         variants=sizes_only(RING_SIZES, stock_each=4)),
    dict(name='Sterling Silver Chain Bracelet', category='Jewelry & Watches', price=4200, compare=None,
         short='Solid curb-link chain, lobster clasp, hand-finished.',
         desc='A solid curb-link chain bracelet cast in sterling silver and hand-polished for a mirror finish, fitted with a secure lobster clasp.',
         sku='AUR-JEW-002', stock=18, featured=False, new=False, material='Sterling silver', weight='14g',
         image='https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&q=80',
         variants=[]),
    dict(name='Automatic Steel Watch', category='Jewelry & Watches', price=28500, compare=32000,
         short='Sapphire crystal, automatic movement, 100m water resistance.',
         desc='Powered by a Swiss automatic movement visible through an exhibition caseback, cased in brushed 316L steel with a scratch-resistant sapphire crystal.',
         sku='AUR-JEW-003', stock=6, featured=True, new=False, material='Steel, sapphire crystal', weight='140g',
         image='https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80',
         variants=colors_only(['Black Dial / Steel', 'White Dial / Steel'], stock_each=3)),
    dict(name='Pearl Drop Earrings', category='Jewelry & Watches', price=6800, compare=None,
         short='Freshwater pearls, 14k gold-filled hooks.',
         desc='Genuine freshwater pearls, each subtly different in shape, suspended from 14k gold-filled ear hooks — a quietly elegant everyday earring.',
         sku='AUR-JEW-004', stock=16, featured=False, new=True, material='Freshwater pearl, gold-filled', weight='6g',
         image='https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80',
         variants=[]),
    dict(name='Vermeil Bar Necklace', category='Jewelry & Watches', price=5200, compare=None,
         short='18k gold vermeil over sterling silver, adjustable chain.',
         desc='A minimal horizontal bar pendant in 18k gold vermeil over solid sterling silver, on a fine adjustable chain that layers well with other pieces.',
         sku='AUR-JEW-005', stock=21, featured=False, new=False, material='18k gold vermeil', weight='4g',
         image='https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80',
         variants=[]),
    dict(name='Enamel Cufflinks', category='Jewelry & Watches', price=3800, compare=None,
         short='Hand-poured navy enamel set in brushed sterling silver.',
         desc='Each pair is individually hand-poured with vitreous enamel and set into a brushed sterling silver surround, presented in a suede-lined box.',
         sku='AUR-JEW-006', stock=17, featured=False, new=False, material='Sterling silver, enamel', weight='14g',
         image='https://images.unsplash.com/photo-1620656798579-1984d9e87df7?w=800&q=80',
         variants=[]),

    # ============ ACCESSORIES ============
    dict(name='Woven Leather Belt', category='Accessories', price=4400, compare=None,
         short='Hand-woven Italian leather with a brushed brass buckle.',
         desc='Individually hand-woven from strips of full-grain Italian leather, finished with a solid brushed-brass buckle that moves with the body.',
         sku='AUR-ACC-001', stock=26, featured=False, new=False, material='Full-grain leather, brass', weight='210g',
         image='https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800&q=80',
         variants=sizes_only(['32', '34', '36', '38'])),
    dict(name='Horn-Rimmed Sunglasses', category='Accessories', price=6900, compare=7900,
         short='Hand-cut acetate frame with polarised grey-green lenses.',
         desc='Cut from a single block of Italian acetate and hand-polished over several days, fitted with polarised UV400 lenses. Comes with a suede case.',
         sku='AUR-ACC-002', stock=14, featured=True, new=False, material='Italian acetate', weight='28g',
         image='https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80',
         variants=colors_only(['Tortoise', 'Black'])),
    dict(name='Silk-Cashmere Scarf', category='Accessories', price=7200, compare=8400,
         short='70/30 silk-cashmere blend, hand-finished fringe.',
         desc='Woven in a light 70/30 silk-cashmere blend that drapes rather than bulks, generously sized at 180x70cm with a hand-twisted fringe.',
         sku='AUR-ACC-003', stock=21, featured=False, new=True, material='Silk-cashmere blend', weight='180g',
         image='https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80',
         variants=colors_only(['Charcoal', 'Rust', 'Ivory'])),
    dict(name='Leather Card Holder Keychain', category='Accessories', price=1800, compare=None,
         short='Vegetable-tanned leather, brass keyring, single card slot.',
         desc='A compact leather card holder that doubles as a keychain, cut from the same vegetable-tanned hide as our wallets for a matching patina over time.',
         sku='AUR-ACC-005', stock=45, featured=False, new=False, material='Vegetable-tanned leather', weight='30g',
         image='https://images.unsplash.com/photo-1612023395494-1c4050b68647?w=800&q=80',
         variants=colors_only(['Tan', 'Black'])),
    dict(name='Silk Pocket Square', category='Accessories', price=2200, compare=None,
         short='Hand-rolled edges, printed silk twill.',
         desc='A pocket square in printed silk twill with hand-rolled edges — a small, considered detail that finishes a jacket.',
         sku='AUR-ACC-006', stock=28, featured=False, new=False, material='Silk twill', weight='25g',
         image='https://images.unsplash.com/photo-1589756823695-278bc923f962?w=800&q=80',
         variants=[]),

    # ============ BEAUTY & FRAGRANCE ============
    dict(name='Eau de Parfum — Vetiver Fig', category='Beauty & Fragrance', price=7400, compare=None,
         short='50ml, green fig leaf over smoked vetiver and cedar.',
         desc='Built around green fig leaf and smoked vetiver, with a quiet cedar and musk base that lasts through the day. Concentrated at 18% for genuine longevity.',
         sku='AUR-BEA-001', stock=18, featured=True, new=True, material='Eau de parfum', weight='180g',
         image='https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80',
         variants=sizes_only(['30ml', '50ml', '100ml'], stock_each=8)),
    dict(name='Sandalwood & Cedar Eau de Parfum', category='Beauty & Fragrance', price=8200, compare=None,
         short='Creamy sandalwood over warm cedar and amber.',
         desc='A warm, woody composition centred on Mysore-style sandalwood, layered with cedar and a soft amber base — equally suited to day or evening wear.',
         sku='AUR-BEA-002', stock=15, featured=True, new=False, material='Eau de parfum', weight='180g',
         image='https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=80',
         variants=sizes_only(['30ml', '50ml', '100ml'], stock_each=7)),
    dict(name='AURA Signature Candle', category='Beauty & Fragrance', price=3200, compare=None,
         short='Coconut-soy wax, cedar and amber, 60-hour burn time.',
         desc='Hand-poured in small batches using a coconut-soy wax blend that burns cleanly and evenly, in the signature cedar-and-amber scent. Approximately 60 hours burn time.',
         sku='AUR-BEA-003', stock=32, featured=True, new=False, material='Coconut-soy wax', weight='320g',
         image='https://images.unsplash.com/photo-1602874801007-bd36c67fa5d7?w=800&q=80',
         variants=[]),
    dict(name='Facial Cleansing Oil', category='Beauty & Fragrance', price=3400, compare=None,
         short='Jojoba and rosehip base, dissolves makeup without stripping skin.',
         desc='A lightweight cleansing oil built on jojoba and rosehip oils that dissolves makeup and daily grime without stripping the skin barrier — rinses clean with no residue.',
         sku='AUR-BEA-004', stock=24, featured=False, new=True, material='Jojoba, rosehip oil', weight='150g',
         image='https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
         variants=[]),
    dict(name='Shea & Oat Body Balm', category='Beauty & Fragrance', price=2600, compare=None,
         short='Whipped shea butter, colloidal oat, fragrance-free.',
         desc='A rich, whipped body balm built on shea butter and colloidal oat, formulated fragrance-free for sensitive skin without sacrificing a genuinely nourishing texture.',
         sku='AUR-BEA-005', stock=29, featured=False, new=False, material='Shea butter, oat', weight='200g',
         image='https://images.unsplash.com/photo-1591019479261-1a5f7069c1d0?w=800&q=80',
         variants=[]),
    dict(name='Grooming Kit — Beard Oil & Balm', category='Beauty & Fragrance', price=2900, compare=None,
         short='Jojoba-based oil and beeswax balm, sandalwood scent.',
         desc='A two-piece grooming set pairing a lightweight jojoba-based beard oil with a beeswax balm for hold, both finished with a warm sandalwood scent.',
         sku='AUR-BEA-006', stock=20, featured=False, new=False, material='Jojoba oil, beeswax', weight='140g',
         image='https://images.unsplash.com/photo-1621607512022-6aecc4fed814?w=800&q=80',
         variants=[]),
    dict(name='Room Diffuser — Santal', category='Beauty & Fragrance', price=4100, compare=None,
         short='200ml reed diffuser, sandalwood and warm spice.',
         desc='A slow-release reed diffuser in a hand-blown glass vessel, filled with a sandalwood, cardamom, and warm spice blend. Rattan reeds included.',
         sku='AUR-BEA-007', stock=21, featured=False, new=False, material='Fragrance oil, glass', weight='420g',
         image='https://images.unsplash.com/photo-1616400619175-5beda3a17896?w=800&q=80',
         variants=[]),

    # ============ HOME & LIVING ============
    dict(name='Sculptural Table Vase', category='Home & Living', price=5400, compare=None,
         short='Matte stoneware in a soft, asymmetric silhouette.',
         desc='Thrown and then hand-altered while the clay is still soft, giving each vase its own gentle asymmetry, finished in a matte bone-tone glaze.',
         sku='AUR-HOM-001', stock=13, featured=False, new=True, material='Stoneware ceramic', weight='1.2kg',
         image='https://images.unsplash.com/photo-1578500351865-d6c3706f46bc?w=800&q=80',
         variants=[]),
    dict(name='Walnut Valet Tray', category='Home & Living', price=3600, compare=None,
         short='Solid walnut, hand-sanded, finished with natural oil.',
         desc='Cut from a single piece of solid American walnut and finished with a food-safe natural oil that deepens the grain over time.',
         sku='AUR-HOM-002', stock=25, featured=False, new=False, material='Solid walnut', weight='390g',
         image='https://images.unsplash.com/photo-1595246140625-573b715d11dc?w=800&q=80',
         variants=[]),
    dict(name='Brushed Brass Bookends', category='Home & Living', price=4800, compare=5600,
         short='Solid cast brass, weighted base, sold as a pair.',
         desc='Cast in solid brass and finished with a soft brushed texture that resists fingerprints, weighted at the base for genuine stability. Sold as a pair.',
         sku='AUR-HOM-003', stock=16, featured=False, new=False, material='Solid cast brass', weight='1.4kg',
         image='https://images.unsplash.com/photo-1616486788371-62d930495c44?w=800&q=80',
         variants=[]),
    dict(name='Linen-Wrapped Storage Box', category='Home & Living', price=2900, compare=None,
         short='Rigid board core wrapped in natural linen, brass corners.',
         desc='A rigid archival board core wrapped by hand in undyed natural linen, finished with solid brass corner protectors.',
         sku='AUR-HOM-004', stock=28, featured=False, new=True, material='Linen, board, brass', weight='450g',
         image='https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80',
         variants=[]),
    dict(name='Minimal Ceramic Table Lamp', category='Home & Living', price=6800, compare=None,
         short='Hand-thrown ceramic base, linen shade, warm LED-ready socket.',
         desc='A table lamp with a hand-thrown ceramic base in a soft matte glaze, paired with a natural linen shade that diffuses light warmly.',
         sku='AUR-HOM-006', stock=12, featured=True, new=False, material='Ceramic, linen', weight='1.8kg',
         image='https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80',
         variants=[]),
    dict(name='Brushed Steel Desk Organizer', category='Home & Living', price=3400, compare=None,
         short='Cold-rolled steel, felt-lined base, modular trays.',
         desc='A modular desk organizer in cold-rolled brushed steel with a felt-lined base to protect surfaces, designed to hold pens, cards, and small tools.',
         sku='AUR-HOM-007', stock=19, featured=False, new=True, material='Brushed steel, felt', weight='620g',
         image='https://images.unsplash.com/photo-1519219788971-8d9797e0dc4f?w=800&q=80',
         variants=[]),

    # ============ LIGHTING & CANDLES ============
    dict(name='Weighted Reading Lamp', category='Lighting & Candles', price=8900, compare=None,
         short='Brushed brass task lamp with a dimmable warm-white LED.',
         desc='A solid brass base gives this lamp genuine heft and stability, while the articulated arm allows precise positioning. Dimmable LED rated for 25 years of daily use.',
         sku='AUR-LGT-001', stock=9, featured=True, new=False, material='Brushed brass, opal glass', weight='2.4kg',
         image='https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
         variants=[]),
    dict(name='Hand-Blown Glass Pendant Light', category='Lighting & Candles', price=9400, compare=None,
         short='Single-piece hand-blown glass shade, brass ceiling rose.',
         desc='A pendant light with a hand-blown glass shade — each one carries the slight asymmetry of being entirely hand-formed — paired with a solid brass ceiling rose.',
         sku='AUR-LGT-002', stock=8, featured=False, new=True, material='Hand-blown glass, brass', weight='980g',
         image='https://images.unsplash.com/photo-1524634126442-357e0eac3c14?w=800&q=80',
         variants=[]),
    # ============ TABLEWARE & KITCHEN ============
    dict(name='Ceramic Pour-Over Set', category='Tableware & Kitchen', price=2890, compare=None,
         short='Hand-thrown stoneware dripper with matching carafe.',
         desc='Each piece is thrown individually on a slow wheel and finished in a matte reactive glaze, meaning no two sets are quite alike. 600ml carafe.',
         sku='AUR-TAB-001', stock=18, featured=False, new=True, material='Stoneware ceramic', weight='950g',
         image='https://images.unsplash.com/photo-1517705008128-361805f42e86?w=800&q=80',
         variants=[]),
    dict(name='Stoneware Dinner Plate Set of 4', category='Tableware & Kitchen', price=6200, compare=None,
         short='Hand-thrown stoneware, matte reactive glaze, 27cm.',
         desc='A set of four hand-thrown dinner plates in a matte reactive glaze that shifts subtly between pieces — dishwasher and microwave safe despite the handmade finish.',
         sku='AUR-TAB-003', stock=14, featured=False, new=False, material='Stoneware ceramic', weight='2.6kg',
         image='https://images.unsplash.com/photo-1584346133934-a3afd2a33c4d?w=800&q=80',
         variants=[]),
    dict(name='Olive Wood Serving Board', category='Tableware & Kitchen', price=3800, compare=None,
         short='Single-slab olive wood, natural edge, food-safe oil finish.',
         desc='Cut from a single slab of olive wood with its natural live edge preserved, finished with a food-safe mineral oil. No two boards are alike in grain.',
         sku='AUR-TAB-004', stock=23, featured=False, new=True, material='Olive wood', weight='780g',
         image='https://images.unsplash.com/photo-1700760933443-84ef4f5feac4?w=800&q=80',
         variants=[]),
    dict(name='Hand-Forged Steel Cheese Knife Set', category='Tableware & Kitchen', price=4400, compare=None,
         short='High-carbon steel, walnut handles, set of 3.',
         desc='A three-piece cheese knife set hand-forged from high-carbon steel with fitted walnut handles, presented in a linen roll.',
         sku='AUR-TAB-005', stock=16, featured=False, new=False, material='Carbon steel, walnut', weight='340g',
         image='https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&q=80',
         variants=[]),

    # ============ TEXTILES & BATH ============
    dict(name='Linen Bath Sheet, Set of 2', category='Textiles & Bath', price=3990, compare=None,
         short='Stonewashed French linen, quick-drying and naturally antibacterial.',
         desc='Woven from long-staple French flax and stonewashed for immediate softness — linen dries faster and breathes better than cotton terry.',
         sku='AUR-TEX-001', stock=30, featured=False, new=False, material='100% French linen', weight='1.1kg',
         image='https://images.unsplash.com/photo-1620811645213-2a53c31768e2?w=800&q=80',
         variants=colors_only(['White', 'Sage'])),
    dict(name='Merino Travel Blanket', category='Textiles & Bath', price=5200, compare=6200,
         short='Featherweight merino throw, folds into its own carry pouch.',
         desc='Woven from 100% extra-fine merino wool in Scotland, warm without weight — ideal for flights or an evening on the terrace. Comes with a matching wool pouch.',
         sku='AUR-TEX-002', stock=15, featured=True, new=False, material='100% merino wool', weight='420g',
         image='https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&q=80',
         variants=[]),
    dict(name='Linen Bedsheet Set', category='Textiles & Bath', price=8900, compare=None,
         short='Stonewashed European linen, fitted + flat + 2 pillowcases.',
         desc='A complete bedsheet set in stonewashed European linen, which softens further with every wash and regulates temperature naturally through the seasons.',
         sku='AUR-TEX-004', stock=12, featured=False, new=False, material='European linen', weight='1.6kg',
         image='https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80',
         variants=sizes_colors(['Queen', 'King'], ['White', 'Clay'], stock_each=4)),

    # ============ STATIONERY & WORKSPACE ============
    dict(name='Leather-Bound A5 Notebook', category='Stationery & Workspace', price=2400, compare=None,
         short='Full-grain leather cover, 192-page cotton paper, refillable.',
         desc='A refillable notebook system with a full-grain leather cover that develops a rich patina, holding a 192-page cotton-paper insert that can be swapped when full.',
         sku='AUR-STA-001', stock=27, featured=False, new=False, material='Full-grain leather', weight='320g',
         image='https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&q=80',
         variants=colors_only(['Tan', 'Black'])),
    dict(name='Brass Fountain Pen', category='Stationery & Workspace', price=3600, compare=None,
         short='Solid brass barrel, stainless steel nib, weighted balance.',
         desc='A solid brass fountain pen that darkens and develops a unique patina with handling, fitted with a smooth German stainless steel nib.',
         sku='AUR-STA-002', stock=19, featured=True, new=False, material='Solid brass, steel', weight='45g',
         image='https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=800&q=80',
         variants=[]),
    dict(name='Cotton Paper Notecard Set', category='Stationery & Workspace', price=1400, compare=None,
         short='100% cotton paper, letterpress-ready, set of 12 with envelopes.',
         desc='A set of twelve blank notecards in heavyweight 100% cotton paper with a soft deckle edge, paired with matching envelopes.',
         sku='AUR-STA-004', stock=35, featured=False, new=True, material='100% cotton paper', weight='180g',
         image='https://images.unsplash.com/photo-1519791883288-dc8bd696e667?w=800&q=80',
         variants=[]),
    dict(name='Leather Desk Mat', category='Stationery & Workspace', price=4900, compare=None,
         short='Full-grain leather, stitched edge, 80x40cm.',
         desc='A full-grain leather desk mat with a hand-stitched edge, large enough to anchor a keyboard and mouse while protecting the desk surface underneath.',
         sku='AUR-STA-005', stock=16, featured=False, new=False, material='Full-grain leather', weight='650g',
         image='https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
         variants=colors_only(['Tan', 'Black', 'Forest Green'])),

    # ============ TECH ACCESSORIES ============
    dict(name='Leather Laptop Sleeve', category='Tech Accessories', price=5400, compare=None,
         short='Full-grain leather, felt lining, fits up to 14-inch laptops.',
         desc='A slim laptop sleeve in full-grain leather with a soft wool-felt lining, sized to fit most 13–14 inch laptops with room for a charger in the front pocket.',
         sku='AUR-TCH-001', stock=22, featured=False, new=False, material='Leather, wool felt', weight='340g',
         image='https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=800&q=80',
         variants=colors_only(['Tan', 'Black'])),
    dict(name='Walnut & Steel Phone Stand', category='Tech Accessories', price=1900, compare=None,
         short='Solid walnut base, brushed steel support, cable channel.',
         desc='A minimal phone stand pairing a solid walnut base with a brushed steel support arm, with a routed channel to keep a charging cable tidy.',
         sku='AUR-TCH-002', stock=30, featured=False, new=True, material='Walnut, brushed steel', weight='280g',
         image='https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&q=80',
         variants=[]),
    dict(name='Braided Charging Cable Set', category='Tech Accessories', price=1600, compare=None,
         short='Braided nylon, reinforced connectors, USB-C, set of 2.',
         desc='A set of two braided nylon charging cables with reinforced aluminium connectors, built to resist fraying far longer than standard rubber-coated cables.',
         sku='AUR-TCH-003', stock=38, featured=False, new=False, material='Braided nylon, aluminium', weight='90g',
         image='https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80',
         variants=[]),
    # ============ TRAVEL ============
    dict(name='Canvas Weekender Bag', category='Travel', price=9800, compare=None,
         short='Waxed canvas body, leather trim, fits airline carry-on.',
         desc='A structured weekender in waxed canvas with full-grain leather trim and reinforced handles, sized to meet most airline carry-on requirements.',
         sku='AUR-TRV-001', stock=13, featured=True, new=False, material='Waxed canvas, leather', weight='1.1kg',
         image='https://images.unsplash.com/photo-1553531384-cc64ac80f931?w=800&q=80',
         variants=colors_only(['Olive', 'Navy'])),
    dict(name='Hardshell Cabin Suitcase', category='Travel', price=14900, compare=17500,
         short='Polycarbonate shell, 360° spinner wheels, TSA lock.',
         desc='A lightweight polycarbonate hardshell cabin case with smooth-rolling 360° spinner wheels and a built-in TSA-approved combination lock.',
         sku='AUR-TRV-002', stock=10, featured=True, new=True, material='Polycarbonate', weight='2.8kg',
         image='https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=800&q=80',
         variants=colors_only(['Charcoal', 'Sand'])),
    dict(name='Leather Passport Holder', category='Travel', price=2600, compare=None,
         short='Full-grain leather, card slots, elastic closure.',
         desc='A slim passport holder in full-grain leather with two card slots and a boarding-pass pocket, secured with a discreet elastic closure.',
         sku='AUR-TRV-003', stock=32, featured=False, new=False, material='Full-grain leather', weight='75g',
         image='https://images.unsplash.com/photo-1553531384-70f4dbdc99d2?w=800&q=80',
         variants=colors_only(['Tan', 'Black', 'Navy'])),
    dict(name='Packable Travel Duffel', category='Travel', price=6200, compare=None,
         short='Ripstop nylon, folds into its own pocket, 45L capacity.',
         desc='A 45L duffel in water-resistant ripstop nylon that folds down into an attached pocket the size of a paperback for easy packing on the way out.',
         sku='AUR-TRV-004', stock=20, featured=False, new=True, material='Ripstop nylon', weight='480g',
         image='https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
         variants=colors_only(['Black', 'Slate'])),
    dict(name='Leather Luggage Tag Set', category='Travel', price=1600, compare=None,
         short='Full-grain leather, brass buckle, set of 2.',
         desc='A pair of full-grain leather luggage tags with a secure brass buckle strap and a windowed pocket for a printed address card.',
         sku='AUR-TRV-005', stock=28, featured=False, new=False, material='Full-grain leather, brass', weight='60g',
         image='https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&q=80',
         variants=[]),
    # ============ ADDITIONAL APPAREL ============
    dict(name='Pleated Midi Skirt', category='Apparel', price=6400, compare=None,
         short='Satin-finish crepe, elastic waist, knife pleats throughout.',
         desc='Fine knife pleats in a satin-finish crepe fabric that hold their shape through wear, on a comfortable elastic waistband hidden beneath a smooth front panel.',
         sku='AUR-APP-012', stock=20, featured=False, new=False, material='Crepe polyester blend', weight='260g',
         image='https://images.unsplash.com/photo-1583496661160-fb5886a13d9c?w=800&q=80',
         variants=sizes_colors(['XS', 'S', 'M', 'L'], ['Champagne', 'Black'])),
    # ============ ADDITIONAL FOOTWEAR ============
    dict(name='Leather Ankle Boot', category='Footwear', price=12800, compare=None,
         short='Full-grain leather, block heel, side zip.',
         desc='A versatile ankle boot in full-grain leather with a comfortable block heel and a concealed side zip for easy wear, finished with a leather sole.',
         sku='AUR-FTW-007', stock=14, featured=False, new=False, material='Full-grain leather', weight='740g',
         image='https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80',
         variants=sizes_colors(['UK4', 'UK5', 'UK6', 'UK7', 'UK8'], ['Black', 'Tan'], stock_each=4)),
    dict(name='Canvas High-Top Sneaker', category='Footwear', price=5400, compare=None,
         short='Heavyweight canvas, reinforced toe cap, rubber sole.',
         desc='A high-top silhouette in heavyweight cotton canvas with a reinforced rubber toe cap and a vulcanized sole built for everyday wear.',
         sku='AUR-FTW-008', stock=27, featured=False, new=False, material='Cotton canvas, rubber', weight='480g',
         image='https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
         variants=sizes_colors(SHOE_SIZES, ['Black', 'Off-White'], stock_each=5)),

    # ============ ADDITIONAL ACCESSORIES ============
    dict(name='Leather Gloves, Lined', category='Accessories', price=4200, compare=None,
         short='Nappa leather, cashmere lining, touchscreen-compatible fingertip.',
         desc='Soft nappa leather gloves lined in genuine cashmere for warmth without bulk, with a touchscreen-compatible index finger and thumb.',
         sku='AUR-ACC-007', stock=22, featured=False, new=True, material='Nappa leather, cashmere', weight='110g',
         image='https://images.unsplash.com/photo-1614251055880-ee96e4803393?w=800&q=80',
         variants=sizes_only(['S', 'M', 'L'])),
    dict(name='Woven Straw Fedora', category='Accessories', price=3800, compare=None,
         short='Hand-woven straw, grosgrain band, packable brim.',
         desc='A hand-woven straw fedora with a grosgrain ribbon band and a flexible brim that packs down for travel without losing its shape.',
         sku='AUR-ACC-008', stock=16, featured=False, new=False, material='Woven straw', weight='140g',
         image='https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800&q=80',
         variants=sizes_only(['S/M', 'L/XL'])),

    # ============ ADDITIONAL HOME & LIVING ============
    dict(name='Rattan Wall Mirror', category='Home & Living', price=5900, compare=None,
         short='Hand-woven rattan frame, round mirror, 60cm diameter.',
         desc='A round wall mirror framed in hand-woven natural rattan, bringing warmth and texture to a wall without the weight of a wood or metal frame.',
         sku='AUR-HOM-008', stock=11, featured=False, new=True, material='Rattan, mirrored glass', weight='1.3kg',
         image='https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80',
         variants=[]),
    dict(name='Woven Jute Area Rug', category='Home & Living', price=8400, compare=None,
         short='Hand-woven jute, natural fibre, 5x7 feet.',
         desc='A hand-woven jute area rug in a natural undyed fibre, adding texture underfoot in an entryway or living space without an overpowering pattern.',
         sku='AUR-HOM-010', stock=9, featured=False, new=False, material='Natural jute', weight='4.2kg',
         image='https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
         variants=[]),

    # ============ ADDITIONAL BEAUTY & FRAGRANCE ============
    # ============ ADDITIONAL TABLEWARE ============
    dict(name='Handblown Wine Glasses, Set of 4', category='Tableware & Kitchen', price=5200, compare=None,
         short='Hand-blown glass, thin rim, stemmed.',
         desc='A set of four hand-blown stemmed wine glasses with a deliberately thin rim for a refined drinking experience, each carrying subtle individual variation.',
         sku='AUR-TAB-006', stock=15, featured=False, new=False, material='Hand-blown glass', weight='1.1kg',
         image='https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=800&q=80',
         variants=[]),
    dict(name='Marble Cheese Board', category='Tableware & Kitchen', price=4600, compare=None,
         short='Polished Makrana marble, brass handle, 35cm.',
         desc='A polished marble serving board with a solid brass handle, doubling as a cool surface for cheese or a striking base for a tablescape.',
         sku='AUR-TAB-007', stock=13, featured=False, new=True, material='Marble, brass', weight='1.8kg',
         image='https://images.unsplash.com/photo-1707079288822-be30b3d1de72?w=800&q=80',
         variants=[]),

    # ============ ADDITIONAL STATIONERY ============
    # ============ ADDITIONAL TECH ACCESSORIES ============

    # ============ NEW PRODUCTS — VERIFIED IMAGES (Unsplash search, alt-text confirmed) ============
    dict(name='Brown Leather Derby Boot', category='Footwear', price=9800, compare=None,
         short='Open lacing, smooth calfskin upper, leather sole.',
         desc='An open-laced derby boot in smooth calfskin, cut for a slightly roomier fit than a Chelsea silhouette while keeping the same clean profile.',
         sku='AUR-FTW-103', stock=16, featured=False, new=False, material='Calfskin leather', weight='700g',
         image='https://images.unsplash.com/photo-1550998358-08b4f83dc345?w=800&q=80',
         variants=sizes_colors(['UK6', 'UK7', 'UK8', 'UK9'], ['Brown'], stock_each=5)),
    dict(name='Black Leather Combat Boot', category='Footwear', price=12200, compare=None,
         short='Rugged full-grain leather, lug sole, reinforced toe.',
         desc='A rugged combat-style boot with a reinforced toe box and deep-lugged rubber sole for grip in poor weather, built from full-grain leather that ages well.',
         sku='AUR-FTW-104', stock=15, featured=False, new=True, material='Full-grain leather', weight='860g',
         image='https://images.unsplash.com/photo-1605732440685-d0654d81aa30?w=800&q=80',
         variants=sizes_colors(['UK6', 'UK7', 'UK8', 'UK9', 'UK10'], ['Black'], stock_each=5)),
    dict(name='Heritage Leather Work Boot', category='Footwear', price=13600, compare=None,
         short='Oil-tanned leather, storm-welt construction, steel shank.',
         desc='A heritage work boot built on a storm-welt construction with a steel shank for support underfoot, cut from oil-tanned leather that resists everyday scuffing.',
         sku='AUR-FTW-106', stock=12, featured=True, new=False, material='Oil-tanned leather', weight='920g',
         image='https://images.unsplash.com/photo-1706587161985-abec97ad6af8?w=800&q=80',
         variants=sizes_colors(['UK7', 'UK8', 'UK9', 'UK10', 'UK11'], ['Brown'], stock_each=4)),
    dict(name='Brown Leather Chukka Boot', category='Footwear', price=8600, compare=None,
         short='Two-eyelet chukka, unlined suede-backed leather, crepe sole.',
         desc='A low two-eyelet chukka boot in suede-backed leather on a lightweight crepe sole — the easiest boot in the lineup to dress up or down.',
         sku='AUR-FTW-107', stock=19, featured=False, new=True, material='Suede-backed leather', weight='560g',
         image='https://images.unsplash.com/photo-1563433337461-5b65f0834f3a?w=800&q=80',
         variants=sizes_colors(['UK6', 'UK7', 'UK8', 'UK9'], ['Tan'], stock_each=5)),
    dict(name='Brown Leather Ankle Bootie', category='Footwear', price=8200, compare=None,
         short='Elasticated side panels, block heel, almond toe.',
         desc='A low ankle bootie with elasticated side panels for an easy slip-on fit, set on a walkable block heel with an almond toe.',
         sku='AUR-FTW-108', stock=17, featured=False, new=False, material='Leather', weight='540g',
         image='https://images.unsplash.com/photo-1534233650908-b471f2350922?w=800&q=80',
         variants=sizes_colors(['UK4', 'UK5', 'UK6', 'UK7'], ['Brown'], stock_each=5)),
    dict(name='Retro Canvas Trainer', category='Footwear', price=4800, compare=None,
         short='Heavyweight canvas upper, vulcanised sole, retro silhouette.',
         desc='A low-top trainer in heavyweight canvas with a vulcanised rubber sole, styled after mid-century court shoes for an easy, everyday silhouette.',
         sku='AUR-FTW-109', stock=30, featured=False, new=True, material='Canvas, rubber', weight='420g',
         image='https://images.unsplash.com/photo-1562105962-2fbaaf107fe3?w=800&q=80',
         variants=sizes_colors(['UK5', 'UK6', 'UK7', 'UK8', 'UK9'], ['Black/White'], stock_each=6)),
    dict(name='Blue Canvas Slip-On Sneaker', category='Footwear', price=4200, compare=None,
         short='Cotton canvas, elastic gusset, cushioned footbed.',
         desc='An easy slip-on sneaker in cotton canvas with an elastic gusset for a snug fit without laces, and a cushioned footbed for all-day wear.',
         sku='AUR-FTW-110', stock=26, featured=False, new=False, material='Cotton canvas', weight='380g',
         image='https://images.unsplash.com/photo-1678192568478-9488ee55def6?w=800&q=80',
         variants=sizes_colors(['UK5', 'UK6', 'UK7', 'UK8'], ['Blue'], stock_each=6)),
    dict(name='Red Canvas High-Top Sneaker', category='Footwear', price=5000, compare=None,
         short='Cotton canvas upper, contrast laces, rubber toe cap.',
         desc='A high-top canvas sneaker with a reinforced rubber toe cap and contrast laces — a bright, casual staple built to be worn hard.',
         sku='AUR-FTW-111', stock=24, featured=False, new=True, material='Cotton canvas', weight='430g',
         image='https://images.unsplash.com/photo-1650320079970-b4ee8f0dae33?w=800&q=80',
         variants=sizes_colors(['UK5', 'UK6', 'UK7', 'UK8'], ['Red'], stock_each=6)),
    dict(name='White Leather Low-Top Sneaker', category='Footwear', price=6400, compare=None,
         short='Smooth leather upper, minimal branding, cupsole.',
         desc='A minimal white leather sneaker built on a cupsole, designed to be re-whitened and worn for years rather than replaced each season.',
         sku='AUR-FTW-112', stock=28, featured=True, new=False, material='Leather', weight='460g',
         image='https://images.unsplash.com/photo-1578269174432-a8073d86c2e0?w=800&q=80',
         variants=sizes_colors(['UK5', 'UK6', 'UK7', 'UK8', 'UK9'], ['White'], stock_each=6)),
    dict(name='Grey Canvas High-Top Sneaker', category='Footwear', price=5200, compare=None,
         short='Washed canvas, metal eyelets, rubber sole.',
         desc='A washed grey canvas high-top with metal eyelets and a durable rubber sole — an easy everyday layer for jeans or joggers.',
         sku='AUR-FTW-113', stock=22, featured=False, new=False, material='Washed canvas', weight='420g',
         image='https://images.unsplash.com/photo-1612942910539-9ff28b2e00d3?w=800&q=80',
         variants=sizes_colors(['UK5', 'UK6', 'UK7', 'UK8'], ['Grey'], stock_each=5)),
    dict(name='Green Suede Sneaker', category='Footwear', price=6800, compare=None,
         short='Brushed suede upper, cotton laces, gum sole.',
         desc='A low-top sneaker in brushed suede with a contrast gum sole — a considered colour for a piece meant to be worn on rotation.',
         sku='AUR-FTW-114', stock=18, featured=False, new=True, material='Suede', weight='440g',
         image='https://images.unsplash.com/photo-1608314122611-583bb07de55d?w=800&q=80',
         variants=sizes_colors(['UK6', 'UK7', 'UK8', 'UK9'], ['Green'], stock_each=5)),
    dict(name='Off-White Canvas High-Top', category='Footwear', price=5400, compare=None,
         short='Cotton canvas, rubber sidewall, cushioned collar.',
         desc='A clean, off-white canvas high-top with a cushioned collar for comfort around the ankle — designed to be re-laced and worn for years.',
         sku='AUR-FTW-115', stock=20, featured=False, new=False, material='Cotton canvas', weight='430g',
         image='https://images.unsplash.com/photo-1787691220334-cda7d4f90c31?w=800&q=80',
         variants=sizes_colors(['UK5', 'UK6', 'UK7', 'UK8'], ['Off-White'], stock_each=5)),
    dict(name='Olive Canvas Trainer', category='Footwear', price=4600, compare=None,
         short='Cotton canvas, white laces, cushioned footbed.',
         desc='An olive canvas trainer with contrast white laces on a cushioned footbed — an easy neutral for warm-weather wardrobes.',
         sku='AUR-FTW-116', stock=25, featured=False, new=False, material='Cotton canvas', weight='400g',
         image='https://images.unsplash.com/photo-1784236404723-bc958ead7dd5?w=800&q=80',
         variants=sizes_colors(['UK5', 'UK6', 'UK7', 'UK8'], ['Olive'], stock_each=6)),

    # ============ NEW JEWELRY & WATCHES ============
    dict(name='Beaded Gold Necklace', category='Jewelry & Watches', price=6200, compare=None,
         short='Gold-plated beads, adjustable clasp, 45cm.',
         desc='A beaded gold-plated necklace on a fine chain with an adjustable clasp — layered alone or with a finer pendant chain.',
         sku='AUR-JEW-101', stock=24, featured=False, new=True, material='Gold-plated brass', weight='18g',
         image='https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=8)),
    dict(name='Fine Gold Chain Necklace', category='Jewelry & Watches', price=7400, compare=None,
         short='18k gold-plated sterling silver, cable chain, 50cm.',
         desc='A fine cable-link chain in 18k gold-plated sterling silver — the everyday layering piece designed to be worn and never taken off.',
         sku='AUR-JEW-102', stock=22, featured=True, new=False, material='Gold-plated sterling silver', weight='9g',
         image='https://images.unsplash.com/photo-1611107683227-e9060eccd846?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=8)),
    dict(name='Beaded Amethyst Necklace', category='Jewelry & Watches', price=5800, compare=None,
         short='Semi-precious beads, gold-filled clasp, 44cm.',
         desc='A hand-strung necklace of semi-precious beads finished with a gold-filled clasp — a considered pop of colour for everyday wear.',
         sku='AUR-JEW-103', stock=16, featured=False, new=False, material='Semi-precious stone, gold-filled', weight='22g',
         image='https://images.unsplash.com/photo-1601121141418-c1caa10a2a0b?w=800&q=80',
         variants=colors_only(['Purple/Gold'], stock_each=6)),
    dict(name='Gold Pendant Necklace', category='Jewelry & Watches', price=6900, compare=None,
         short='14k gold-plated pendant, fine chain, lobster clasp.',
         desc='A single geometric pendant on a fine 14k gold-plated chain — a minimal everyday piece that layers well with a longer chain.',
         sku='AUR-JEW-104', stock=20, featured=False, new=True, material='Gold-plated brass', weight='7g',
         image='https://images.unsplash.com/photo-1569397288884-4d43d6738fbd?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=8)),
    dict(name='Gold Heart Charm Necklace', category='Jewelry & Watches', price=6400, compare=None,
         short='Gold-plated heart charm, adjustable chain, gift box.',
         desc='A gold-plated heart charm on a fine adjustable chain, presented in a gift box — a considered, easy gift.',
         sku='AUR-JEW-105', stock=18, featured=False, new=False, material='Gold-plated brass', weight='6g',
         image='https://images.unsplash.com/photo-1623321673989-830eff0fd59f?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=6)),
    dict(name='Layered Gold Necklace Set', category='Jewelry & Watches', price=8600, compare=9800,
         short='Two-piece layering set, two chain lengths, matching clasp.',
         desc='A two-piece layering set pairing a shorter collarbone chain with a longer pendant chain, designed to be worn together or separately.',
         sku='AUR-JEW-106', stock=14, featured=True, new=True, material='Gold-plated brass', weight='14g',
         image='https://images.unsplash.com/photo-1705326454924-f6777522b030?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=5)),
    dict(name='Red Beaded Statement Necklace', category='Jewelry & Watches', price=5200, compare=None,
         short='Hand-strung glass beads, gold-tone spacers.',
         desc='A hand-strung statement necklace in warm red glass beads with gold-tone spacers between each bead — a bold finishing piece.',
         sku='AUR-JEW-107', stock=15, featured=False, new=False, material='Glass beads, gold-tone metal', weight='26g',
         image='https://images.unsplash.com/photo-1600862754152-80a263dd564f?w=800&q=80',
         variants=colors_only(['Red/Gold'], stock_each=5)),
    dict(name='Pearl and Gold Necklace', category='Jewelry & Watches', price=7800, compare=None,
         short='Freshwater pearls, gold-plated chain, 42cm.',
         desc='Freshwater pearls set along a fine gold-plated chain — a modern take on a classic pairing, light enough for daily wear.',
         sku='AUR-JEW-108', stock=17, featured=False, new=True, material='Freshwater pearl, gold-plated brass', weight='16g',
         image='https://images.unsplash.com/photo-1721103418312-b0057a8c31c2?w=800&q=80',
         variants=colors_only(['Pearl/Gold'], stock_each=5)),
    dict(name='Gold Turtle Charm Necklace', category='Jewelry & Watches', price=5600, compare=None,
         short='Gold-plated charm pendant, fine chain.',
         desc='A playful gold-plated charm pendant on a fine chain — a lighthearted everyday piece that still reads considered.',
         sku='AUR-JEW-109', stock=19, featured=False, new=False, material='Gold-plated brass', weight='6g',
         image='https://images.unsplash.com/photo-1722410180644-ff76ef805092?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=6)),
    dict(name='Gold Hoop Earrings', category='Jewelry & Watches', price=4800, compare=None,
         short='14k gold-plated, medium hoop, secure hinge closure.',
         desc='A medium gold-plated hoop earring with a secure hinge closure — the everyday earring built to be worn on rotation without tarnishing.',
         sku='AUR-JEW-110', stock=30, featured=True, new=False, material='Gold-plated brass', weight='4g',
         image='https://images.unsplash.com/photo-1708220040824-b273dd0a17cc?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=10)),
    dict(name='Silver Hoop Earrings', category='Jewelry & Watches', price=3800, compare=None,
         short='Sterling silver, small hoop, butterfly back.',
         desc='A small sterling silver hoop earring finished with a secure butterfly back — a clean everyday pair that pairs with anything.',
         sku='AUR-JEW-111', stock=32, featured=False, new=False, material='Sterling silver', weight='3g',
         image='https://images.unsplash.com/photo-1765464281313-b3844388b316?w=800&q=80',
         variants=colors_only(['Silver'], stock_each=10)),
    dict(name='Gold Sparkle Hoop Earrings', category='Jewelry & Watches', price=5400, compare=None,
         short='Gold-plated, textured finish, medium hoop.',
         desc='A textured gold-plated hoop with a subtle sparkle finish that catches the light without being a full statement piece.',
         sku='AUR-JEW-112', stock=22, featured=False, new=True, material='Gold-plated brass', weight='5g',
         image='https://images.unsplash.com/photo-1781901726877-0b5775eea722?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=7)),
    dict(name='Diamond-Cut Stud Earrings', category='Jewelry & Watches', price=6200, compare=None,
         short='Gold-plated, faceted setting, secure push back.',
         desc='A pair of faceted gold-plated stud earrings on a secure push back — small enough for daily wear, bright enough to notice.',
         sku='AUR-JEW-113', stock=24, featured=False, new=False, material='Gold-plated brass', weight='2g',
         image='https://images.unsplash.com/photo-1771173652661-8245a9d94095?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=8)),
    dict(name='Textured Gold Hoop Earrings', category='Jewelry & Watches', price=5000, compare=None,
         short='Gold-plated, hammered texture, medium hoop.',
         desc='A pair of hammered-texture gold-plated hoops that catch light differently to a smooth hoop — a considered everyday upgrade.',
         sku='AUR-JEW-114', stock=20, featured=False, new=False, material='Gold-plated brass', weight='5g',
         image='https://images.unsplash.com/photo-1781901726815-29af905d0b46?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=6)),
    dict(name='Gold Chain-Link Hoop Earrings', category='Jewelry & Watches', price=5600, compare=None,
         short='Gold-plated, chain-link design, lightweight.',
         desc='A chain-link hoop earring in lightweight gold-plated brass, designed to move without pulling on the ear.',
         sku='AUR-JEW-115', stock=18, featured=False, new=True, material='Gold-plated brass', weight='6g',
         image='https://images.unsplash.com/photo-1786052337390-567bce745609?w=800&q=80',
         variants=colors_only(['Gold'], stock_each=6)),

    # ============ NEW BAGS & WALLETS ============
    dict(name='Slim Leather Cardholder Wallet', category='Bags & Wallets', price=2400, compare=None,
         short='Vegetable-tanned leather, four card slots, RFID-blocking.',
         desc='A slim, RFID-blocking cardholder cut from vegetable-tanned leather with four card slots and a central note pocket — built for a front-pocket carry.',
         sku='AUR-BAG-101', stock=32, featured=False, new=True, material='Vegetable-tanned leather', weight='45g',
         image='https://images.unsplash.com/photo-1629958513881-a086d21383cd?w=800&q=80',
         variants=colors_only(['Black', 'Brown'], stock_each=10)),
    dict(name='Classic Bifold Leather Wallet', category='Bags & Wallets', price=3200, compare=None,
         short='Full-grain leather, six card slots, bill compartment.',
         desc='A classic bifold wallet in full-grain leather with six card slots and a full-width bill compartment, hand-stitched along every edge.',
         sku='AUR-BAG-102', stock=26, featured=True, new=False, material='Full-grain leather', weight='90g',
         image='https://images.unsplash.com/photo-1606503825008-909a67e63c3d?w=800&q=80',
         variants=colors_only(['Brown', 'Black'], stock_each=8)),
    dict(name='Everyday Leather Trifold Wallet', category='Bags & Wallets', price=3000, compare=None,
         short='Full-grain leather, trifold construction, ID window.',
         desc='A trifold wallet in full-grain leather with a clear ID window and eight card slots — a practical daily-carry piece.',
         sku='AUR-BAG-105', stock=24, featured=False, new=False, material='Full-grain leather', weight='105g',
         image='https://images.unsplash.com/photo-1531190260877-c8d11eb5afaf?w=800&q=80',
         variants=colors_only(['Brown', 'Black'], stock_each=8)),

    # ============ NEW TABLEWARE & KITCHEN ============
    dict(name='Acacia Wood Serving Board', category='Tableware & Kitchen', price=3800, compare=None,
         short='Solid acacia wood, 40cm, food-safe oil finish.',
         desc='A generous solid-acacia serving board finished with food-safe oil, sized for a full spread of cheese, charcuterie, and fruit.',
         sku='AUR-TAB-101', stock=16, featured=False, new=True, material='Acacia wood', weight='1.4kg',
         image='https://images.unsplash.com/photo-1727975399471-1d6f8ce91bbb?w=800&q=80',
         variants=[]),
    dict(name='Rustic Grazing Board', category='Tableware & Kitchen', price=4200, compare=None,
         short='Reclaimed hardwood, live edge, brass ring handle.',
         desc='A live-edge grazing board in reclaimed hardwood with a brass ring handle — built for entertaining, no two boards exactly alike.',
         sku='AUR-TAB-102', stock=12, featured=False, new=False, material='Reclaimed hardwood', weight='1.6kg',
         image='https://images.unsplash.com/photo-1627935722051-395636b0d8a5?w=800&q=80',
         variants=[]),

    # ============ NEW PRODUCTS (catalog-fix pass, image-verified via live source lookup) ============
    dict(name='Belted Wool Trench Coat', category='Outerwear', price=15800, compare=None,
         short='Double-breasted wool trench with a self-tie belt.',
         desc='A city trench cut from a heavyweight wool blend, with a double-breasted front, storm flap, and self-tie belt at the waist. Falls just below the knee for a clean, tailored silhouette over both suiting and knitwear.',
         sku='AUR-OUT-008', stock=14, featured=False, new=True, material='Wool blend', weight='980g',
         image='https://images.unsplash.com/photo-1737508945707-ebdccee97cc5?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Camel'])),
    dict(name='Single-Breasted Wool Overcoat', category='Outerwear', price=17200, compare=None,
         short='Brown single-breasted overcoat in brushed wool.',
         desc='A single-breasted overcoat in brushed wool with horn buttons and a notch lapel. Fully canvassed through the chest for structure that holds its shape wear after wear.',
         sku='AUR-OUT-009', stock=12, featured=False, new=True, material='Brushed wool', weight='1.1kg',
         image='https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Brown'])),
    dict(name='Charcoal Wool Overcoat', category='Outerwear', price=17200, compare=None,
         short="Men's charcoal wool overcoat with a two-button front.",
         desc='A tailored two-button overcoat in charcoal wool suiting, cut with a slight A-line for ease of movement over a jacket. Half-lined in Bemberg for a clean drape.',
         sku='AUR-OUT-010', stock=13, featured=False, new=False, material='Wool suiting', weight='1.15kg',
         image='https://images.unsplash.com/photo-1619603364937-8d7af41ef206?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Charcoal'])),
    dict(name='Houndstooth Wool Jacket', category='Outerwear', price=13600, compare=None,
         short='Cropped houndstooth wool jacket with patch pockets.',
         desc='A cropped jacket woven in a classic black-and-white houndstooth, finished with patch pockets and a single-button closure. Wool-blend construction holds structure without added stiffness.',
         sku='AUR-OUT-011', stock=15, featured=True, new=True, material='Wool blend', weight='720g',
         image='https://images.unsplash.com/photo-1649566169356-e47e8d9809e4?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Houndstooth'])),
    dict(name='Ivory Double-Breasted Wool Coat', category='Outerwear', price=18400, compare=None,
         short='Ivory double-breasted coat in soft wool.',
         desc='An ivory double-breasted coat in a soft, brushed wool, with a wide notch lapel and horn buttons. A considered alternative to black or camel for anyone building a lighter-toned outerwear rotation.',
         sku='AUR-OUT-012', stock=9, featured=False, new=True, material='Brushed wool', weight='1.05kg',
         image='https://images.unsplash.com/photo-1680690395101-1b2a56c0ac21?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Ivory'])),
    dict(name='Classic White Linen Shirt', category='Apparel', price=5200, compare=None,
         short='Crisp white shirt in washed European linen.',
         desc='A clean, classic shirt cut from washed European linen, with a spread collar and single-button barrel cuffs. The relaxed body skims rather than clings, and softens further with every wash.',
         sku='AUR-APP-013', stock=26, featured=False, new=True, material='European linen', weight='210g',
         image='https://images.unsplash.com/photo-1591357037205-166318b51afd?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['White'])),
    dict(name='Chambray Cotton Shirt', category='Apparel', price=5400, compare=None,
         short='Mid-weight chambray shirt with a workwear collar.',
         desc='A mid-weight cotton chambray shirt with a workwear-inspired collar and chest pocket. Garment-dyed for a soft, slightly faded hand-feel straight out of the box.',
         sku='AUR-APP-014', stock=24, featured=False, new=False, material='Cotton chambray', weight='230g',
         image='https://images.unsplash.com/photo-1582261484646-a545de6d2382?w=800&q=80',
         variants=sizes_colors(APPAREL_SIZES, ['Chambray Blue'])),
    dict(name='Multi-Wick Jar Candle', category='Lighting & Candles', price=3400, compare=None,
         short='Three-wick soy candle in a clear glass jar.',
         desc='A generous three-wick candle poured in small batches from a soy-coconut wax blend, set in a clear glass jar so the wicks and wax are visible from every angle. Roughly 60 hours of burn time.',
         sku='AUR-LGT-003', stock=30, featured=False, new=True, material='Soy-coconut wax, glass', weight='620g',
         image='https://images.unsplash.com/photo-1643122966676-29e8597257f7?w=800&q=80',
         variants=colors_only(['Amber Woods'], stock_each=15)),
    dict(name='Amber Glass Pillar Candle', category='Lighting & Candles', price=2600, compare=None,
         short='Hand-poured pillar candle in an amber glass vessel.',
         desc='A single-wick pillar candle hand-poured into a reusable amber glass vessel, designed to sit on a nightstand or dining table long after the wax is gone. Clean-burning coconut wax blend.',
         sku='AUR-LGT-004', stock=28, featured=False, new=False, material='Coconut wax, amber glass', weight='340g',
         image='https://images.unsplash.com/photo-1714228499605-367154d9bdb2?w=800&q=80',
         variants=colors_only(['Santal Amber'], stock_each=14)),
    dict(name='Checkered Glass Votive Candle Duo', category='Lighting & Candles', price=2200, compare=None,
         short='Two mini votive candles in checkered glass holders.',
         desc='A pair of mini votive candles set in checkered glass holders, sold together for grouping along a mantel or table runner. Each burns for approximately 18 hours.',
         sku='AUR-LGT-005', stock=32, featured=False, new=True, material='Paraffin-soy blend, glass', weight='260g',
         image='https://images.unsplash.com/photo-1631021967299-59d54f546248?w=800&q=80',
         variants=[]),
    dict(name='Stoneware Dinner Set, Service for 4', category='Tableware & Kitchen', price=7800, compare=None,
         short='16-piece glazed stoneware dinnerware set.',
         desc='A 16-piece stoneware set — four each of dinner plates, side plates, bowls, and mugs — hand-glazed in small batches, so no two pieces are perfectly identical. Dishwasher and microwave safe.',
         sku='AUR-TAB-103', stock=17, featured=True, new=True, material='Glazed stoneware', weight='4.8kg',
         image='https://images.unsplash.com/photo-1551807306-4bcd16b92a41?w=800&q=80',
         variants=colors_only(['Warm White', 'Slate Grey'], stock_each=9)),
    dict(name='Coastal Blue Bath Towel Set', category='Textiles & Bath', price=3800, compare=None,
         short='Set of three combed-cotton towels in coastal blue.',
         desc='A set of three combed-cotton towels — bath sheet, hand towel, and washcloth — woven at a dense 600 GSM for absorbency that holds up over years of washing. Finished in a soft coastal blue.',
         sku='AUR-TEX-005', stock=22, featured=False, new=True, material='Combed cotton, 600 GSM', weight='1.4kg',
         image='https://images.unsplash.com/photo-1728034261564-18930dcb2c8e?w=800&q=80',
         variants=colors_only(['Coastal Blue'], stock_each=11)),

]


DEMO_REVIEWERS = [
    ('ananya.k', 'Ananya', 'Kapoor'),
    ('rohan.m', 'Rohan', 'Mehta'),
    ('priya.s', 'Priya', 'Sharma'),
    ('arjun.n', 'Arjun', 'Nair'),
    ('divya.r', 'Divya', 'Rao'),
    ('karan.b', 'Karan', 'Bose'),
]

DEMO_REVIEW_TEXTS = [
    (5, "The quality is genuinely something else — you can tell it's built to last, not just to look good in a photo. Worth every rupee."),
    (5, "Ordered on a whim and now I understand why people rave about AURA. The material feels premium and the finish is flawless."),
    (4, "Really lovely piece. Sizing ran slightly generous for me but the quality more than makes up for it."),
    (5, "This has quickly become something I reach for constantly. Understated but clearly well made when you look closely."),
    (4, "Beautiful craftsmanship. Shipping took a couple of days longer than expected but the product itself is excellent."),
    (5, "Exactly as described — the photos don't even do the texture and finish justice. Already planning my next order."),
]

COUPONS = [
    dict(code='AURA10', discount_type='percentage', discount_value=10, minimum_order_amount=0),
    dict(code='WELCOME15', discount_type='percentage', discount_value=15, minimum_order_amount=2000),
    dict(code='FLAT500', discount_type='fixed', discount_value=500, minimum_order_amount=3500),
]


class Command(BaseCommand):
    help = 'Bootstraps the AURA catalog safely without overwriting existing database data.'

    def handle(self, *args, **options):
        # IMPORTANT: The database is the source of truth after initial bootstrap.
        # If products already exist, this command must never overwrite, recreate,
        # or delete administrator-managed catalog records.
        bootstrap = not Product.objects.exists()

        if bootstrap:
            self.stdout.write('Bootstrapping categories...')
            category_map = {}
            for i, cat in enumerate(CATEGORIES):
                obj, created = Category.objects.get_or_create(
                    slug=slugify(cat['name']),
                    defaults={
                        'name': cat['name'],
                        'description': cat['description'],
                        'image_url': cat['image'],
                        'display_order': i,
                        'is_active': True,
                    },
                )
                category_map[cat['name']] = obj
            self.stdout.write(self.style.SUCCESS(f'  {len(category_map)} categories ready.'))

            self.stdout.write('Bootstrapping products and variants...')
            created_count = 0
            variant_count = 0
            product_objs = []

            for p in PRODUCTS:
                obj, created = Product.objects.get_or_create(
                    sku=p['sku'],
                    defaults={
                        'name': p['name'],
                        'category': category_map[p['category']],
                        'short_description': p['short'],
                        'description': p['desc'],
                        'price': Decimal(str(p['price'])),
                        'compare_at_price': Decimal(str(p['compare'])) if p['compare'] else None,
                        'stock_quantity': p['stock'],
                        'is_featured': p['featured'],
                        'is_new_arrival': p['new'],
                        'is_active': True,
                        'material': p['material'],
                        'weight': p['weight'],
                        'image_url': p['image'],
                    },
                )
                product_objs.append(obj)
                if created:
                    created_count += 1

                # Variants are part of the initial bootstrap only. Once the
                # database exists, admin changes/additions/deletions are preserved.
                for idx, spec in enumerate(p.get('variants') or []):
                    size = spec.get('size', '')
                    color = spec.get('color', '')
                    material = spec.get('material', '')
                    sku_bits = [p['sku']]
                    if color:
                        sku_bits.append(color[:3].upper())
                    if size:
                        sku_bits.append(size.replace('/', ''))
                    variant_sku = '-'.join(sku_bits)
                    _, v_created = ProductVariant.objects.get_or_create(
                        sku=variant_sku,
                        defaults={
                            'product': obj,
                            'size': size,
                            'color': color,
                            'material': material,
                            'stock_quantity': spec.get('stock', 10),
                            'is_default': idx == 0,
                            'is_active': True,
                        },
                    )
                    if v_created:
                        variant_count += 1

            self.stdout.write(self.style.SUCCESS(
                f'  Products created: {created_count}. Variants created: {variant_count}.'
            ))
        else:
            # Existing database: deliberately do not reconcile seed definitions
            # against live records. This protects admin edits, additions, and
            # deletions from being reset by a later seed command.
            category_map = {c.slug: c for c in Category.objects.all()}
            product_objs = list(Product.objects.all())
            self.stdout.write(self.style.WARNING(
                f'Existing database detected ({len(product_objs)} products). '
                'Preserving all existing categories, products, and variants; no catalog records will be overwritten or recreated.'
            ))

        self.stdout.write('Seeding demo reviewers and reviews...')
        reviewers = []
        for username, first, last in DEMO_REVIEWERS:
            user, _ = User.objects.get_or_create(
                username=username,
                defaults={'first_name': first, 'last_name': last, 'email': f'{username}@example.com'},
            )
            if not user.has_usable_password():
                user.set_unusable_password()
                user.save()
            reviewers.append(user)

        review_count = 0
        rated_products = [p for p in product_objs if p.is_featured or p.is_new_arrival][:24]
        for idx, product in enumerate(rated_products):
            reviewer = reviewers[idx % len(reviewers)]
            rating, text = DEMO_REVIEW_TEXTS[idx % len(DEMO_REVIEW_TEXTS)]
            _, created = Review.objects.get_or_create(
                product=product, user=reviewer,
                defaults={'rating': rating, 'comment': text, 'is_verified_purchase': True},
            )
            if created:
                review_count += 1
        self.stdout.write(self.style.SUCCESS(f'  {review_count} demo reviews seeded.'))

        self.stdout.write('Seeding demo coupons...')
        coupon_count = 0
        for c in COUPONS:
            # Coupons are also admin-managed data; only create a missing demo
            # coupon and never overwrite an existing coupon's settings.
            _, created = Coupon.objects.get_or_create(
                code=c['code'],
                defaults={
                    'discount_type': c['discount_type'],
                    'discount_value': Decimal(str(c['discount_value'])),
                    'minimum_order_amount': Decimal(str(c['minimum_order_amount'])),
                    'active': True,
                },
            )
            if created:
                coupon_count += 1
        self.stdout.write(self.style.SUCCESS(f'  {coupon_count} demo coupons created if missing.'))

        self.stdout.write(self.style.SUCCESS(
            f'Done. {len(category_map) if bootstrap else Category.objects.count()} categories, '
            f'{Product.objects.count()} products total. Database changes were preserved.'
        ))
