# Generated by Django 6.1 on 2026-08-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='External editorial image representing this category.'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=30)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('material', models.CharField(blank=True, max_length=80)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the base product price for this variant.', max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
