# Generated by Django 6.1 on 2026-08-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_update_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'Match System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10),
        ),
    ]
